In [1]:
import numpy as np 

In [2]:
#标量
s = 5
#向量
v = np.array( [1,2] )
#矩阵
m = np.array( [ [1,2] , [3,4] ] )
#张量
t = np.array([
    [ [1,2,3] , [4,5,6] , [7,8,9] ],
    
    [ [1,2,3] , [4,5,6] , [7,8,9] ],
    
    [ [1,2,3] , [4,5,6] , [7,8,9] ],
])



print("标量：" + str(s))
print("向量：" + str(v))
print("矩阵：" + str(m))
print("张量：" + str(t))

标量：5
向量：[1 2]
矩阵：[[1 2]
 [3 4]]
张量：[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [3]:
#A是矩阵。A_t是A的转置矩阵。
A = np.array(   [  [1,0,2,0]    ,   [1,0,0,0]   ,   [2,0,3,0]   ]   )
A_t = A.transpose()

print("A:",A)

print("A_T :", A_t)



A: [[1 0 2 0]
 [1 0 0 0]
 [2 0 3 0]]
A_T : [[1 1 2]
 [0 0 0]
 [2 0 3]
 [0 0 0]]


In [4]:
#矩阵相加
a = np.array(   [   [1,2,3,4,5] ,   [6,7,8,9,10]    ]   )
b = np.array(   [   [2,3,4,5,6] ,   [7,8,9,10,11]   ]   )
print("矩阵相加：" , a + b)


矩阵相加： [[ 3  5  7  9 11]
 [13 15 17 19 21]]


In [5]:
m1 = np.array(  [   [1,2,3,4,5]   ,  [6,7,8,9,10]  ]   )
m2 = np.array(  [   [1,2]   ,   [2,3]   ,   [4,5]   ,   [6,7]   ,   [8,9]   ]   )

print("按矩阵乘法规则："    ,   np.dot(m1,m2))
#print("按逐元素相乘："      ,   np.multiply(m1,m2))
#print("按逐元素相乘："      ,   m1*m2)

print("按逐元素相乘："      ,   np.multiply(a,b))
print("按逐元素相乘："      ,   a*b)

v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])
print("向量内积：", np.dot(v1,v2))



按矩阵乘法规则： [[ 81  96]
 [186 226]]
按逐元素相乘： [[  2   6  12  20  30]
 [ 42  56  72  90 110]]
按逐元素相乘： [[  2   6  12  20  30]
 [ 42  56  72  90 110]]
向量内积： 130


In [6]:
print(" " , np.dot(m1,np.identity(5)))

np.identity(4)

#np.identity是定义单位矩阵的函数

  [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:

#print("m1的逆矩阵:" , np.linalg.inv(m1))

print(np.identity(4))


print("逆矩阵:", np.linalg.inv(np.identity(4)))

print("m逆矩阵:",np.linalg.inv(m))

print()

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
逆矩阵: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
m逆矩阵: [[-2.   1. ]
 [ 1.5 -0.5]]



In [8]:
def inverse(number):
    return 1 / number

#print(inverse(0))
print(inverse(1))


1.0


In [9]:
from cmath import pi


print("v1",v1)

v3 = np.array([2,3,4,5,6,7,8])

print("v2",v2)

print("v3",v3)

print("向量v1的L0范数:",np.linalg.norm(v1,ord=0))
print("向量v1的L1范数:",np.linalg.norm(v1,ord=1))
print("向量v1的L5范数:" , np.linalg.norm(v1,ord=5))

print("向量v2的L1范数:",np.linalg.norm(v2,ord=1))
print("向量v2的L2范数:",np.linalg.norm(v2,ord=2))

print("向量v2的无穷范数:",np.linalg.norm(v2,ord=np.Inf))

print("向量v3的L0范数:",np.linalg.norm(v3,ord=0))
print("向量v3的无穷范数:",np.linalg.norm(v3,ord=np.Inf))

print("a",a)
print("矩阵a的F范数:",np.linalg.norm(a,ord="fro"))

v1 [1 2 3 4 5]
v2 [ 6  7  8  9 10]
v3 [2 3 4 5 6 7 8]
向量v1的L0范数: 5.0
向量v1的L1范数: 15.0
向量v1的L5范数: 5.360220495669696
向量v2的L1范数: 40.0
向量v2的L2范数: 18.16590212458495
向量v2的无穷范数: 10.0
向量v3的L0范数: 7.0
向量v3的无穷范数: 8.0
a [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
矩阵a的F范数: 19.621416870348583
